version: "3.8"

services:
  node:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-buster
    restart: always
    
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root