version: "3.8"

services:
  node:
    image: mcr.microsoft.com/vscode/devcontainers/typescript-node:0-14-buster
    restart: always
    # keep running container
    command: tail -F anything /dev/null
    volumes:
      - .:/workspace
    ports: 
      - 8086:8086
    
  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
  
volumes:
  mongodata: